### ISSUE TITLE
Hello，comrade.

### ISSUE THREAD

**Issue by cloudilychy** [DiazoPlus/gaussian-basis-sets#1]
你好，同志。我从负责https://github.com/ProletRevDicta/Prolet的mega网盘和AI扫描的cannedpork（qq账号）那儿得知你们搞了个网站。我是个对马列毛主义产生兴趣不久的新人，想进一步学习马列毛主义，可以告诉我你们网站的网址吗？

**Comment by DiazoPlus** [comment]
该事项与本仓库无关，请移步至https://github.com/ProletRevDicta/Prolet/issues

----

你需要的东西可以在这里找到https://github.com/ProletRevDicta/Prolet/commit/8263cce8fe6efa384b4852df5428ffd2b48cf94a
